### ISSUE TITLE
1.19 Fabric (Sodium) crash

### ISSUE THREAD

**Issue by MatheusZanfolin** [TelepathicGrunt/Bumblezone#124]
A few minutes after entering the new dimension, the game crashed.
Upon reentering, the game, this time, crashed almost instantly after loading the world
More details on the crash report: https://pastebin.com/z1DcS53D

Both running Sodium: the first one with the Complementary Reimagined shaders and the second crash (the one detailed on the report) without any shaders

**Comment by TelepathicGrunt** [comment]
This is the stacktrace remapped:

   at net.minecraft.util.thread.LockHelper.crash(LockHelper.java:84)
    at net.minecraft.util.math.random.CheckedRandom.next(CheckedRandom.java:49)
    at net.minecraft.util.math.random.BaseRandom.nextInt(BaseRandom.java:33)
    at net.minecraft.world.SpawnHelper.spawnEntitiesInChunk(SpawnHelper.java:246)
    at net.minecraft.world.SpawnHelper.spawnEntitiesInChunk(SpawnHelper.java:212)
    at net.minecraft.world.SpawnHelper.spawn(SpawnHelper.java:200)
    at net.minecraft.server.world.ServerChunkManager.tickChunks(ServerChunkManager.java:376)
    at net.minecraft.server.world.ServerChunkManager.tick(ServerChunkManager.java:323)
    at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:318)
    at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:875)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:98)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:665)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
    at java.base/java.lang.Thread.run(Thread.java:833)
    
 This crash is happening with purely vanilla code. Another thread is accessing the world's random at the same time on another thread and causing the crash. However, the log does not show what that other thread is and finding out is extremely difficult.

**Comment by TelepathicGrunt** [comment]
Please try again with v6.1.0 bumblezone. Maybe I inadvertently fixed the crash as I cleaned up my random usages

**Comment by MatheusZanfolin** [comment]
Just did that, and it seemed pretty stable! Spent a few minutes digging my way out of the beehive and didn't face any crashes, thankfully, so I believe the problem may be solved 🙂
