### ISSUE TITLE
Server crash, referencing the_bumblezone:player_component, but I don't have Bumblezone installed. 

### ISSUE THREAD

**Issue by purejosh** [TelepathicGrunt/Bumblezone#196]
Hey TG, got a weird one. I'm running a couple mods from you, but not Bumblezone. I had a server crash, and it references only built in Minecraft classes, except an error message that comes from Bumblezone. It's weird. I'm trying to find out if this is an effect, or a cause. Mind taking a peek? 

Crash:
https://gist.github.com/purejosh/f2d131bbad3ab2b9abfb904a4a77cdad

Server log: (starts five minutes before the crash)
https://gist.github.com/purejosh/071de539b62b125217fe44c146325943

**Comment by TelepathicGrunt** [comment]
I don't see any error message from Bumblezone
Remapped stacktrace: https://paste.ee/p/ohO8r

Also, crash is not a Bumblezone issue. You got a mod in your pack that is accessing randomsources unsafely and causing a crash. Most likely on  another thread. Detail of the issue explained in this other issue report: https://github.com/team-abnormals/savage-and-ravage/issues/119

Without a thread dump somehow done exactly when the crash occurs, there is no way to know which mod/mob is the issue that is accessing the server's random source on the off thread unsafely. Bumblezone already fixed all it's own random source issues and I even patched vanilla bee's random source usage so vanilla bees worldgen spawning is now also threadsafe.

**Comment by purejosh** [comment]
This is the reference I found with bumblezone in it:
```
[12:28:36] [Worker-Main-2084/ERROR]: Hanging entity at invalid position: class_2338{x=-404, y=59, z=19}
[12:28:36] [Worker-Main-2084/ERROR]: Hanging entity at invalid position: class_2338{x=-404, y=59, z=18}
[12:28:36] [Worker-Main-2084/ERROR]: Hanging entity at invalid position: class_2338{x=-404, y=58, z=18}
[12:28:36] [Worker-Main-2084/ERROR]: Hanging entity at invalid position: class_2338{x=-400, y=58, z=18}
[12:28:36] [Worker-Main-2084/ERROR]: Hanging entity at invalid position: class_2338{x=-400, y=59, z=19}
[12:28:37] [Worker-Main-2004/ERROR]: Hanging entity at invalid position: class_2338{x=-126, y=8, z=-76}
[12:28:37] [Worker-Main-2004/ERROR]: Hanging entity at invalid position: class_2338{x=-124, y=8, z=-76}
[12:28:37] [Worker-Main-2004/ERROR]: Hanging entity at invalid position: class_2338{x=-122, y=8, z=-76}
[12:28:37] [Worker-Main-2004/WARN]: Failed to deserialize component: unregistered key the_bumblezone:player_component
[12:28:37] [Worker-Main-2003/ERROR]: Hanging entity at invalid position: class_2338{x=-146, y=6, z=-88}
[12:28:37] [Worker-Main-2003/ERROR]: Hanging entity at invalid position: class_2338{x=-146, y=6, z=-92}
[12:28:37] [Worker-Main-2003/ERROR]: Hanging entity at invalid position: class_2338{x=-144, y=6, z=-88}
[12:28:37] [Worker-Main-2003/ERROR]: Hanging entity at invalid position: class_2338{x=-144, y=6, z=-93}
[12:28:37] [Worker-Main-2003/ERROR]: Hanging entity at invalid position: class_2338{x=-144, y=6, z=-92}
[12:28:37] [Server thread/ERROR]: Thread dumps: 
Server thread: 
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
	at net.minecraft.class_5798.method_39936(class_5798.java:92)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.minecraft.class_5798.method_33564(class_5798.java:82)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:33)
	at net.minecraft.class_1948.method_24930(class_1948.java:247)
	at net.minecraft.class_1948.method_8663(class_1948.java:212)
	at net.minecraft.class_1948.redirect$bgb000$spawnMultipleTimes(class_1948.java:1834)
	at net.minecraft.class_1948.method_27821(class_1948.java:200)
	at net.minecraft.class_3215.redirect$cad000$injectSpawn(class_3215.java:2608)
	at net.minecraft.class_3215.method_14161(class_3215.java:376)
	at net.minecraft.class_3215.method_12127(class_3215.java:323)
	at net.minecraft.class_3218.method_18765(class_3218.java:319)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.handler$bdf000$modifiedRunLoop(MinecraftServer.java:6885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
[12:28:37] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bdf000$modifiedRunLoop(MinecraftServer.java:6885) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.class_5798.method_33564(class_5798.java:84) ~[server-intermediary.jar:?]
	at net.minecraft.class_5820.method_43156(class_5820.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.class_6566.method_43048(class_6566.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_1948.method_24930(class_1948.java:247) ~[server-intermediary.jar:?]
	at net.minecraft.class_1948.method_8663(class_1948.java:212) ~[server-intermediary.jar:?]
	at net.minecraft.class_1948.redirect$bgb000$spawnMultipleTimes(class_1948.java:1834) ~[server-intermediary.jar:?]
	at net.minecraft.class_1948.method_27821(class_1948.java:200) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215.redirect$cad000$injectSpawn(class_3215.java:2608) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215.method_14161(class_3215.java:376) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215.method_12127(class_3215.java:323) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:319) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[server-intermediary.jar:?]
	... 6 more
[12:28:37] [Server thread/ERROR]: This crash report has been saved to: C:\Users\minecraft\Desktop\Crafty Controller\servers\427bf195-0b5c-484e-a7b2-468c5e214ac6\.\crash-reports\crash-2023-01-20_12.28.37-server.txt
[12:28:37] [Server thread/INFO]: [STDOUT]: Saving server results
[12:28:37] [Server thread/INFO]: [STDOUT]: Saving config results
[12:28:37] [Server thread/INFO]: Starting shutdown process...
[12:28:37] [Server thread/INFO]: Closing messaging service...
[12:28:37] [Server thread/INFO]: Closing storage...
[12:28:37] [Server thread/INFO]: luckperms-hikari - Shutdown initiated...
[12:28:37] [Server thread/INFO]: luckperms-hikari - Shutdown completed.
[12:28:37] [Server thread/INFO]: Goodbye!
[12:28:37] [Server thread/INFO]: Stopping server
[12:28:37] [Server thread/INFO]: Saving players
[12:28:37] [Server thread/INFO]: TriHardPoio lost connection: multiplayer.disconnect.server_shutdown
[12:28:37] [Server thread/INFO]: [JoinLeaveMessages] Suppressing a join/leave message
[12:28:37] [Server thread/INFO]: Updating all forceload tickets for e4276147-7731-42f7-b5b6-384f8fa10aeb
[12:28:37] [Server thread/INFO]: Dag7 lost connection: multiplayer.disconnect.server_shutdown
[12:28:37] [Server thread/INFO]: [JoinLeaveMessages] Suppressing a join/leave message
[12:28:37] [Server thread/INFO]: Updating all forceload tickets for 9ce7998e-17c3-4441-91cc-78458f3474b1
[12:28:37] [Server thread/INFO]: Saving worlds
[12:28:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[12:28:52] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/paradise_lost:paradise_lost
[12:28:53] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/twilightforest:twilight_forest
[12:28:53] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[12:28:55] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/deeperdarker:otherside
[12:28:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[12:28:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[12:28:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (paradise_lost): All chunks are saved
[12:28:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (twilight_forest): All chunks are saved
[12:28:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:28:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (otherside): All chunks are saved
[12:28:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:28:56] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[12:29:12] [Server thread/INFO]: Unloading addons...
[12:29:12] [Server thread/INFO]: Unloaded addons
[12:29:12] [Server thread/INFO]: Unloading instance: net.dv8tion.jda.internal.JDAImpl@441f750c
[12:29:12] [Server thread/INFO]: Unloading listener: de.erdbeerbaerlp.dcintegration.common.DiscordEventListener@760bf6bb
[12:29:12] [Server thread/INFO]: Stopping IO worker...
[12:29:12] [Server thread/INFO]: Stopped IO worker!
```

**Comment by purejosh** [comment]
Specifically `Failed to deserialize component: unregistered key the_bumblezone:player_component`

It's probably nothing though, I'm literally grasping at straws.

**Comment by TelepathicGrunt** [comment]
that's just means a component on the player wasn't able to be read. player_component does not exist in my codebase ever since 1.18+. I am assuming this is an old world from 1.17 or older you ported to a newer mc version because the player had an old component name that was later replaced. The old data wont be able to be read anymore. 

There is no issue that will be caused by the old data being unabled to be parse. Because the components now are entity_component, original_flying_speed, neurotoxins_missed_counter, essence_component, misc_component and those are created automatically on the player and will be read just fine.

Also this doesn't have anything to do with the random source crash.

**Comment by purejosh** [comment]
Appreciate the insight.
