### ISSUE TITLE
Log spam involving "missing capability"

### ISSUE THREAD

**Issue by IzzelAliz** [TelepathicGrunt/Bumblezone#23]
Version 1.15.2-1.3.10

Forge 31.2.45

Spam after player leaving server.

Logs
<details>
<pre>
[20Oct2020 10:16:04.574] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: asdzjx lost connection: Timed out
[20Oct2020 10:16:04.579] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: asdzjx left the game
[20Oct2020 10:16:04.647] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 9
	Listeners:
		0: NORMAL
		1: ASM: class andrews.pandoras_creatures.util.RehostedJarHandler onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		2: ASM: class andrews.pandoras_creatures.events.EventHandler onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		3: net.minecraftforge.eventbus.EventBus$$Lambda$2794/0x0000000840c6e440@4b4329fc
		4: ASM: class com.teammetallurgy.atum.items.artifacts.atum.LegsOfAtumItem onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		5: ASM: class com.teammetallurgy.atum.items.artifacts.nuit.NuitsVanishingItem onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		6: ASM: class com.teammetallurgy.atum.items.artifacts.ra.LegsOfRaItem onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		7: ASM: class com.teammetallurgy.atum.misc.event.AtumEventListener playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		8: ASM: class com.maciej916.maenchants.ForgeEventSubscriber onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		9: ASM: class net.telepathicgrunt.bumblezone.entities.PlayerTeleportationBehavior$ForgeEvents playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		10: ASM: class net.telepathicgrunt.bumblezone.entities.BeeAggressionBehavior$ForgeEvents playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		11: ASM: class com.teamabnormals.upgrade_aquatic.core.events.EntityEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		12: ASM: class com.robertx22.mine_and_slash.onevent.ontick.OnServerTick onTickLogicVoid(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		13: ASM: invtweaks.InvTweaksMod@6e22aac0 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		14: ASM: class net.tropicraft.core.common.item.scuba.ScubaData onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		15: ASM: net.blay09.mods.netherportalfix.NetherPortalFix@5b9ef80e onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		16: ASM: gigaherz.toolbelt.slot.BeltExtensionSlot$EventHandlers@1bb1db95 entityTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		17: ASM: vazkii.quark.tweaks.module.CampfiresBoostElytraModule@18d482d6 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		18: ASM: vazkii.quark.tweaks.module.CompassesWorkEverywhereModule@3d14fd3c onUpdate(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		19: ASM: vazkii.quark.tweaks.module.EnhancedLaddersModule@4e00dd8d onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		20: ASM: com.natamus.areas.events.AreaEvent@695b9fd2 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		21: ASM: class com.mushroom.midnight.common.config.MidnightConfig tick(Lnet/minecraftforge/event/TickEvent;)V
java.lang.RuntimeException
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:261)
	at net.telepathicgrunt.bumblezone.entities.PlayerTeleportationBehavior$ForgeEvents.playerTick(PlayerTeleportationBehavior.java:181)
	at net.minecraftforge.eventbus.ASMEventHandler_628_ForgeEvents_playerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:84)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntityMixin.java:206)
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntityMixin.java:361)
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandlerMixin.java:183)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManagerMixin.java:228)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:866)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:330)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:784)
	at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1973)
	at java.base/java.lang.Thread.run(Thread.java:834)

[20Oct2020 10:16:04.665] [Server thread/WARN] [net.minecraft.network.NetworkSystem/]: Failed to handle packet for /117.44.167.196:6457
net.minecraft.crash.ReportedException: Ticking player
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntityMixin.java:424) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandlerMixin.java:183) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManagerMixin.java:228) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:866) [?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:330) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:784) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1973) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.RuntimeException
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:261) ~[?:?]
	at net.telepathicgrunt.bumblezone.entities.PlayerTeleportationBehavior$ForgeEvents.playerTick(PlayerTeleportationBehavior.java:181) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler_628_ForgeEvents_playerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:84) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntityMixin.java:206) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntityMixin.java:361) ~[?:?]
	... 8 more
[20Oct2020 10:16:04.725] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 9
	Listeners:
		0: NORMAL
		1: ASM: class andrews.pandoras_creatures.util.RehostedJarHandler onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		2: ASM: class andrews.pandoras_creatures.events.EventHandler onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		3: net.minecraftforge.eventbus.EventBus$$Lambda$2794/0x0000000840c6e440@4b4329fc
		4: ASM: class com.teammetallurgy.atum.items.artifacts.atum.LegsOfAtumItem onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		5: ASM: class com.teammetallurgy.atum.items.artifacts.nuit.NuitsVanishingItem onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		6: ASM: class com.teammetallurgy.atum.items.artifacts.ra.LegsOfRaItem onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		7: ASM: class com.teammetallurgy.atum.misc.event.AtumEventListener playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		8: ASM: class com.maciej916.maenchants.ForgeEventSubscriber onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		9: ASM: class net.telepathicgrunt.bumblezone.entities.PlayerTeleportationBehavior$ForgeEvents playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		10: ASM: class net.telepathicgrunt.bumblezone.entities.BeeAggressionBehavior$ForgeEvents playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		11: ASM: class com.teamabnormals.upgrade_aquatic.core.events.EntityEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		12: ASM: class com.robertx22.mine_and_slash.onevent.ontick.OnServerTick onTickLogicVoid(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		13: ASM: invtweaks.InvTweaksMod@6e22aac0 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		14: ASM: class net.tropicraft.core.common.item.scuba.ScubaData onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		15: ASM: net.blay09.mods.netherportalfix.NetherPortalFix@5b9ef80e onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		16: ASM: gigaherz.toolbelt.slot.BeltExtensionSlot$EventHandlers@1bb1db95 entityTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		17: ASM: vazkii.quark.tweaks.module.CampfiresBoostElytraModule@18d482d6 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		18: ASM: vazkii.quark.tweaks.module.CompassesWorkEverywhereModule@3d14fd3c onUpdate(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		19: ASM: vazkii.quark.tweaks.module.EnhancedLaddersModule@4e00dd8d onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		20: ASM: com.natamus.areas.events.AreaEvent@695b9fd2 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		21: ASM: class com.mushroom.midnight.common.config.MidnightConfig tick(Lnet/minecraftforge/event/TickEvent;)V
java.lang.RuntimeException
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:261)
	at net.telepathicgrunt.bumblezone.entities.PlayerTeleportationBehavior$ForgeEvents.playerTick(PlayerTeleportationBehavior.java:181)
	at net.minecraftforge.eventbus.ASMEventHandler_628_ForgeEvents_playerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:84)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntityMixin.java:206)
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntityMixin.java:361)
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandlerMixin.java:183)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManagerMixin.java:228)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:866)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:330)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:784)
	at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1973)
	at java.base/java.lang.Thread.run(Thread.java:834)

[20Oct2020 10:16:04.729] [Server thread/WARN] [net.minecraft.network.NetworkSystem/]: Failed to handle packet for /117.44.167.196:6457
net.minecraft.crash.ReportedException: Ticking player
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntityMixin.java:424) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandlerMixin.java:183) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManagerMixin.java:228) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:866) [?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:330) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:784) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1973) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.RuntimeException
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:261) ~[?:?]
	at net.telepathicgrunt.bumblezone.entities.PlayerTeleportationBehavior$ForgeEvents.playerTick(PlayerTeleportationBehavior.java:181) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler_628_ForgeEvents_playerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:84) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntityMixin.java:206) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntityMixin.java:361) ~[?:?]
	... 8 more
[20Oct2020 10:16:04.788] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 9
	Listeners:
		0: NORMAL
		1: ASM: class andrews.pandoras_creatures.util.RehostedJarHandler onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		2: ASM: class andrews.pandoras_creatures.events.EventHandler onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		3: net.minecraftforge.eventbus.EventBus$$Lambda$2794/0x0000000840c6e440@4b4329fc
		4: ASM: class com.teammetallurgy.atum.items.artifacts.atum.LegsOfAtumItem onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		5: ASM: class com.teammetallurgy.atum.items.artifacts.nuit.NuitsVanishingItem onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		6: ASM: class com.teammetallurgy.atum.items.artifacts.ra.LegsOfRaItem onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		7: ASM: class com.teammetallurgy.atum.misc.event.AtumEventListener playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		8: ASM: class com.maciej916.maenchants.ForgeEventSubscriber onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		9: ASM: class net.telepathicgrunt.bumblezone.entities.PlayerTeleportationBehavior$ForgeEvents playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		10: ASM: class net.telepathicgrunt.bumblezone.entities.BeeAggressionBehavior$ForgeEvents playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		11: ASM: class com.teamabnormals.upgrade_aquatic.core.events.EntityEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		12: ASM: class com.robertx22.mine_and_slash.onevent.ontick.OnServerTick onTickLogicVoid(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		13: ASM: invtweaks.InvTweaksMod@6e22aac0 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		14: ASM: class net.tropicraft.core.common.item.scuba.ScubaData onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		15: ASM: net.blay09.mods.netherportalfix.NetherPortalFix@5b9ef80e onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		16: ASM: gigaherz.toolbelt.slot.BeltExtensionSlot$EventHandlers@1bb1db95 entityTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		17: ASM: vazkii.quark.tweaks.module.CampfiresBoostElytraModule@18d482d6 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		18: ASM: vazkii.quark.tweaks.module.CompassesWorkEverywhereModule@3d14fd3c onUpdate(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		19: ASM: vazkii.quark.tweaks.module.EnhancedLaddersModule@4e00dd8d onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		20: ASM: com.natamus.areas.events.AreaEvent@695b9fd2 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		21: ASM: class com.mushroom.midnight.common.config.MidnightConfig tick(Lnet/minecraftforge/event/TickEvent;)V
java.lang.RuntimeException
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:261)
	at net.telepathicgrunt.bumblezone.entities.PlayerTeleportationBehavior$ForgeEvents.playerTick(PlayerTeleportationBehavior.java:181)
	at net.minecraftforge.eventbus.ASMEventHandler_628_ForgeEvents_playerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:84)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntityMixin.java:206)
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntityMixin.java:361)
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandlerMixin.java:183)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManagerMixin.java:228)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:866)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:330)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:784)
	at net.minecraft.server.MinecraftServer.run(MinecraftServerMixin.java:1973)
	at java.base/java.lang.Thread.run(Thread.java:834)

</pre>
</details>

**Comment by TelepathicGrunt** [comment]
Hey, thank you reaching out to me! However, I do not support any Minecraft versions older than the latest (1.16.3) as I do not have to time to handle maintaining all my mods for every version. If another modder wants to come in and PR fixes into older versions of my mod, they are free to do so!
