### ISSUE TITLE
Crash When Throwing Enderpearl to Beehive

### ISSUE THREAD

**Issue by Jafooleryy** [TelepathicGrunt/Bumblezone#264]
My game crashes when try to enter a beehive through an enderpearl, i grab a beehive from creative and place it then try to enter it and it crashes. I only have fabric api and bumblezone installed. Here is the crash report

[18:39:06] [Server thread/ERROR]:
 Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: morethanhidden/restrictedportals/RPCommon
	at com.telepathicgrunt.the_bumblezone.modcompat.fabricbase.RestrictedPortalsCompat.isDimensionDisallowed(RestrictedPortalsCompat.java:12) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.utils.fabric.PlatformHooksImpl.isDimensionAllowed(PlatformHooksImpl.java:221) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.utils.PlatformHooks.isDimensionAllowed(PlatformHooks.java) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.world.dimension.BzWorldSavedData.teleportEntityAndAssignToVehicle(BzWorldSavedData.java:272) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.world.dimension.BzWorldSavedData.baseTeleporting(BzWorldSavedData.java:248) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.world.dimension.BzWorldSavedData.lambda$enteringBumblezone$6(BzWorldSavedData.java:232) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at com.telepathicgrunt.the_bumblezone.world.dimension.BzWorldSavedData.enteringBumblezone(BzWorldSavedData.java:216) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.world.dimension.BzWorldSavedData.tick(BzWorldSavedData.java:163) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.world.dimension.BzWorldSavedData.worldTick(BzWorldSavedData.java:88) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.events.base.EventHandler.invoke(EventHandler.java:25) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.fabric.FabricEventManager.lambda$init$3(FabricEventManager.java:91) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:63) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-2797ff451c2ba64e.jar:?]
	at net.minecraft.class_3218.handler$zef000$fabric-lifecycle-events-v1$endWorldTick(class_3218.java:2740) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:396) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[client-intermediary.jar:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: morethanhidden.restrictedportals.RPCommon
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at com.telepathicgrunt.the_bumblezone.modcompat.fabricbase.RestrictedPortalsCompat.isDimensionDisallowed(RestrictedPortalsCompat.java:12) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.utils.fabric.PlatformHooksImpl.isDimensionAllowed(PlatformHooksImpl.java:221) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.utils.PlatformHooks.isDimensionAllowed(PlatformHooks.java) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.world.dimension.BzWorldSavedData.teleportEntityAndAssignToVehicle(BzWorldSavedData.java:272) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.world.dimension.BzWorldSavedData.baseTeleporting(BzWorldSavedData.java:248) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.world.dimension.BzWorldSavedData.lambda$enteringBumblezone$6(BzWorldSavedData.java:232) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at com.telepathicgrunt.the_bumblezone.world.dimension.BzWorldSavedData.enteringBumblezone(BzWorldSavedData.java:216) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.world.dimension.BzWorldSavedData.tick(BzWorldSavedData.java:163) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.world.dimension.BzWorldSavedData.worldTick(BzWorldSavedData.java:88) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.events.base.EventHandler.invoke(EventHandler.java:25) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at com.telepathicgrunt.the_bumblezone.fabric.FabricEventManager.lambda$init$3(FabricEventManager.java:91) ~[the_bumblezone-7.0.1+1.20.1-fabric.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:63) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-2797ff451c2ba64e.jar:?]
	at net.minecraft.class_3218.handler$zef000$fabric-lifecycle-events-v1$endWorldTick(class_3218.java:2740) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:396) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[client-intermediary.jar:?]
	... 5 more
[18:39:06] [Server thread/ERROR]:
 This crash report has been saved to: C:\Users\Itsya\AppData\Roaming\com.modrinth.theseus\profiles\bee\crash-reports\crash-2023-09-20_18.39.06-server.txt
[18:39:06] [Server thread/INFO]:
 Stopping server

**Comment by TelepathicGrunt** [comment]
Should be now fixed in v7.0.2. Jars should be approved on all sites in a few minutes
