### ISSUE TITLE
Invalid resource keys

### ISSUE THREAD

**Issue by AngellusMortis** [TelepathicGrunt/Bumblezone#279]
While tracking down an issue a world gen issue, I came across this error with [Cydanide](https://github.com/alcatrazEscapee/cyanide) loaded ([details on what it means](https://github.com/alcatrazEscapee/cyanide/issues/5)). It looks like Bumblezone has some resource keys set wrong.

```
Errors(s) loading registry minecraft:worldgen/biome:

Optional field "music" was invalid: Failed to get element ResourceKey[minecraft:sound_event / the_bumblezone:biome_music]
Optional field "ambient_sound" was invalid: Failed to get element ResourceKey[minecraft:sound_event / the_bumblezone:beehive_ambience]
	at: "effects"
	at: worldgen/biome 'the_bumblezone:worldgen/biome/crystal_canyon.json'
	at: pack 'the_bumblezone-7.0.15+1.20.1-forge.jar'
Optional field "music" was invalid: Failed to get element ResourceKey[minecraft:sound_event / the_bumblezone:biome_music]
Optional field "ambient_sound" was invalid: Failed to get element ResourceKey[minecraft:sound_event / the_bumblezone:beehive_ambience]
	at: "effects"
	at: worldgen/biome 'the_bumblezone:worldgen/biome/floral_meadow.json'
	at: pack 'the_bumblezone-7.0.15+1.20.1-forge.jar'
Optional field "music" was invalid: Failed to get element ResourceKey[minecraft:sound_event / the_bumblezone:biome_music]
Optional field "ambient_sound" was invalid: Failed to get element ResourceKey[minecraft:sound_event / the_bumblezone:beehive_ambience]
	at: "effects"
	at: worldgen/biome 'the_bumblezone:worldgen/biome/hive_pillar.json'
	at: pack 'the_bumblezone-7.0.15+1.20.1-forge.jar'
Optional field "music" was invalid: Failed to get element ResourceKey[minecraft:sound_event / the_bumblezone:biome_music]
Optional field "ambient_sound" was invalid: Failed to get element ResourceKey[minecraft:sound_event / the_bumblezone:beehive_ambience]
	at: "effects"
	at: worldgen/biome 'the_bumblezone:worldgen/biome/hive_wall.json'
	at: pack 'the_bumblezone-7.0.15+1.20.1-forge.jar'
Optional field "music" was invalid: Failed to get element ResourceKey[minecraft:sound_event / the_bumblezone:biome_music]
	at: "effects"
	at: worldgen/biome 'the_bumblezone:worldgen/biome/howling_constructs.json'
	at: pack 'the_bumblezone-7.0.15+1.20.1-forge.jar'
Optional field "music" was invalid: Failed to get element ResourceKey[minecraft:sound_event / the_bumblezone:biome_music]
Optional field "ambient_sound" was invalid: Failed to get element ResourceKey[minecraft:sound_event / the_bumblezone:beehive_ambience]
	at: "effects"
	at: worldgen/biome 'the_bumblezone:worldgen/biome/pollinated_fields.json'
	at: pack 'the_bumblezone-7.0.15+1.20.1-forge.jar'
Optional field "music" was invalid: Failed to get element ResourceKey[minecraft:sound_event / the_bumblezone:biome_music]
Optional field "ambient_sound" was invalid: Failed to get element ResourceKey[minecraft:sound_event / the_bumblezone:beehive_ambience]
	at: "effects"
	at: worldgen/biome 'the_bumblezone:worldgen/biome/pollinated_pillar.json'
	at: pack 'the_bumblezone-7.0.15+1.20.1-forge.jar'
Optional field "music" was invalid: Failed to get element ResourceKey[minecraft:sound_event / the_bumblezone:biome_music]
Optional field "ambient_sound" was invalid: Failed to get element ResourceKey[minecraft:sound_event / the_bumblezone:beehive_ambience]
	at: "effects"
	at: worldgen/biome 'the_bumblezone:worldgen/biome/sugar_water_floor.json'
	at: pack 'the_bumblezone-7.0.15+1.20.1-forge.jar'

	at com.alcatrazescapee.cyanide.codec.MixinHooks.loadAllRegistryData(MixinHooks.java:137) ~[cyanide-forge-1.20-4.0.0.jar%23422!/:4.0.0]
	at net.minecraft.resources.RegistryDataLoader.handler$ehp000$loadAndReportErrors(RegistryDataLoader.java:1019) ~[client-1.20.1-20230612.114412-srg.jar%23564!/:?]
	at net.minecraft.resources.RegistryDataLoader.m_247207_(RegistryDataLoader.java) ~[client-1.20.1-20230612.114412-srg.jar%23564!/:?]
	at net.minecraft.server.WorldLoader.m_246152_(WorldLoader.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23564!/:?]
	at net.minecraft.server.WorldLoader.m_245736_(WorldLoader.java:58) ~[client-1.20.1-20230612.114412-srg.jar%23564!/:?]
	at net.minecraft.server.WorldLoader.m_214362_(WorldLoader.java:31) ~[client-1.20.1-20230612.114412-srg.jar%23564!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_246486_(WorldOpenFlows.java:162) ~[client-1.20.1-20230612.114412-srg.jar%23564!/:?]
	... 37 more
```

**Comment by TelepathicGrunt** [comment]
fixed in v7.0.16
