### ISSUE TITLE
[1.20.1 Fabric] Crashes During the Sanctum Event due to Origins mod

### ISSUE THREAD

**Issue by Scryzze** [TelepathicGrunt/Bumblezone#292]
Shooting the floating crystals during the sanctum event causes the following error and subsequent crash; this causes the world to be unplayable as it simply crashes upon being loaded again.

Happens on the version the_bumblezone-7.0.25+1.20.1-fabric of the mod.

`java.lang.NullPointerException: Cannot invoke "java.util.Optional.isPresent()" because "this.apoli$shouldApplyArmor" is null
	at net.minecraft.class_1309.handler$zca000$apoli$modifyArmorApplicance(class_1309.java:5329)
	at net.minecraft.class_1309.method_6132(class_1309.java)
	at net.minecraft.class_1309.method_6074(class_1309.java:1683)
	at com.telepathicgrunt.the_bumblezone.entities.living.CosmicCrystalEntity.method_5643(CosmicCrystalEntity.java:1423)
	at net.minecraft.class_1665.method_7454(class_1665.java:374)
	at net.minecraft.class_1676.method_7488(class_1676.java:153)
	at net.minecraft.class_1665.method_5773(class_1665.java:227)
	at net.minecraft.class_1667.method_5773(class_1667.java:104)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by TelepathicGrunt** [comment]
The log is showing apoli trying to apply armor to my armor-less living entity. (apoli might author name of some other mod you have on) Disable that mod to enter your world again. Have you reported this to them?

**Comment by TelepathicGrunt** [comment]
Apoli seems to be a part of origins. They are attaching a field to my entity by mixin. But not populating that field themselves. And then crash later when trying to access the field. I don't see what I can do as it seems to be exclusively their code that's not safe

https://github.com/apace100/apoli/blob/5895cf5df1ee37e41eab86b0881f3fa3eb235356/src/main/java/io/github/apace100/apoli/mixin/LivingEntityMixin.java#L177C37-L177C53

**Comment by Scryzze** [comment]
Ah, didn't catch that it was apoli and not Bumblezone. Strangely enough it is only that specific entity that has this issue, none of the others added by the mod. Thank you for going ahead and bringing it up with the right person; I'll go ahead and close this issue as it looks like there's nothing you can do on your end.

**Comment by TelepathicGrunt** [comment]
I decided to backport Apoli's 1.20.2 fix to 1.20.1 by making a small mixin mod to specifically fix this
https://legacy.curseforge.com/minecraft/mc-mods/origins-apoli-armor-mixin-fix

This will stop the crash with Bumblezone
