### ISSUE TITLE
ERRORSomething broke when trying to add mod compatibility with quark. Please let The Bumblezone developer (TelepathicGrunt) know about this!

### ISSUE THREAD

**Issue by ModernGamingWorld** [TelepathicGrunt/Bumblezone#354]
https://gist.github.com/ModernGamingWorld/90307871e0088385a90e35cb1024d7f9

This is all it said when the server started up for mc version 1.20.1, so it just told me to report it lol.

**Comment by TelepathicGrunt** [comment]
Are you using latest Bumblezone? I updated the compat with latest Quark at the time after their package renaming

**Comment by ModernGamingWorld** [comment]
@TelepathicGrunt Yes I am using the_bumblezone-7.2.9+1.20.1-forge.jar

**Comment by ghost** [comment]
I'm having the same error!

```
[Render thread/ERROR] [co.te.th.Bumblezone/]:   ------------------------------------------------NOTICE-------------------------------------------------------------------------

  ERROR: Something broke when trying to add mod compatibility with quark. Please let The Bumblezone developer (TelepathicGrunt) know about this!

  ------------------------------------------------NOTICE-------------------------------------------------------------------------

java.lang.UnsupportedOperationException
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.add(ImmutableCollections.java:147)
	at TRANSFORMER/the_bumblezone@7.2.9+1.20.1-forge/com.telepathicgrunt.the_bumblezone.modcompat.forge.QuarkCompat.setupEnchantmentTooltipItemsSymbols(QuarkCompat.java:21)
	at TRANSFORMER/the_bumblezone@7.2.9+1.20.1-forge/com.telepathicgrunt.the_bumblezone.modcompat.forge.QuarkCompat.<init>(QuarkCompat.java:13)
	at TRANSFORMER/the_bumblezone@7.2.9+1.20.1-forge/com.telepathicgrunt.the_bumblezone.modcompat.forge.ForgeModChecker.lambda$setupModCompat$1(ForgeModChecker.java:31)
	at TRANSFORMER/the_bumblezone@7.2.9+1.20.1-forge/com.telepathicgrunt.the_bumblezone.modcompat.ModChecker.loadupModCompat(ModChecker.java:111)
	at TRANSFORMER/the_bumblezone@7.2.9+1.20.1-forge/com.telepathicgrunt.the_bumblezone.modcompat.forge.ForgeModChecker.setupModCompat(ForgeModChecker.java:31)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at LAYER PLUGIN/fmlcore@1.20.1-47.2.20/net.minecraftforge.fml.DeferredWorkQueue.lambda$makeRunnable$2(DeferredWorkQueue.java:81)
	at LAYER PLUGIN/fmlcore@1.20.1-47.2.20/net.minecraftforge.fml.DeferredWorkQueue.makeRunnable(DeferredWorkQueue.java:76)
	at LAYER PLUGIN/fmlcore@1.20.1-47.2.20/net.minecraftforge.fml.DeferredWorkQueue.lambda$runTasks$0(DeferredWorkQueue.java:60)
	at java.base/java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650)
	at LAYER PLUGIN/fmlcore@1.20.1-47.2.20/net.minecraftforge.fml.DeferredWorkQueue.runTasks(DeferredWorkQueue.java:60)
	at TRANSFORMER/forge@47.2.20/net.minecraftforge.fml.core.ParallelTransition.lambda$finalActivityGenerator$2(ParallelTransition.java:35)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
	```

**Comment by TelepathicGrunt** [comment]
Ah quark make it an immutable list. Fun

@SkightMeow its no concern on user end. I catch mod compat loading issues so it doesn’t crash game. The only lost behavior is Bumblezone items won’t show up as enchantable for enchantment in quark’s purely informational tooltip on enchanted books.

**Comment by TelepathicGrunt** [comment]
Going to remove this compat code out of Bumblezone entirely

To reproduce the same compat, add these items to quark's enchantingStacks config option
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/9df59d7e-88f4-4cd5-8301-3e03b6731c1e)
