### ISSUE TITLE
[1.19.2 QUILT] Incompat with Sprinks

### ISSUE THREAD

**Issue by Sunconure11** [TelepathicGrunt/Bumblezone#377]
https://gist.github.com/Sunconure11/604d80f7f631c6f768af2461ad57a664

Found this while testing out some more obscure mods.

https://www.curseforge.com/minecraft/mc-mods/sprinks

Unfortunately, you will likely have to decompile the mod to see what is going on.

**Comment by TelepathicGrunt** [comment]
```

Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [#sprinks:sprinks.mixins.json:HolderMixins$InventoryChangedCriterionConditionsMixin from mod sprinks] from phase [DEFAULT] in config [#sprinks:sprinks.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 22 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Specified index 0 for @ModifyArg is invalid for args (Lnet/minecraft/class_2073;Lnet/minecraft/class_1799;), expected Lnet/minecraft/class_1799; on net/minecraft/class_2066$class_2068::changeTestItem [INJECT Applicator Phase -> #sprinks:sprinks.mixins.json:HolderMixins$InventoryChangedCriterionConditionsMixin from mod sprinks -> Apply Injections ->  -> Inject -> #sprinks:sprinks.mixins.json:HolderMixins$InventoryChangedCriterionConditionsMixin from mod sprinks->@ModifyArg::changeTestItem(Lnet/minecraft/class_1799;)Lnet/minecraft/class_1799;]

```

sprinks has a broken mixin. Nothing I can do. They will need to fix their mixin on their end

**Comment by TelepathicGrunt** [comment]
Closing as this seems to be in Sprinks's ballpark to handle
