### ISSUE TITLE
[1.21] Bumblezone teleporting breaks with C2ME

### ISSUE THREAD

**Issue by makumaku1974** [TelepathicGrunt/Bumblezone#401]
![2024-06-21_13 32 24](https://github.com/TelepathicGrunt/Bumblezone/assets/129804277/810f8dc6-535d-4ed5-952b-b42d57130405)

**Comment by makumaku1974** [comment]
Log : 
[2024-06-21-3.log.gz](https://github.com/user-attachments/files/15923320/2024-06-21-3.log.gz)

**Comment by TelepathicGrunt** [comment]
Entry from log for reference

```
[13:29:29] [bumblezone_locator_and_teleportation-1-thread-1/ERROR]: Bumblezone: Failed to teleport entity. Error:
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Chunk not there when requested: Unloaded chunk
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179) ~[?:?]
	at net.minecraft.class_9761.method_60452(class_9761.java:215) ~[client-intermediary.jar:?]
	at net.minecraft.class_9761.method_60460(class_9761.java:206) ~[client-intermediary.jar:?]
	at net.minecraft.class_9761.method_60454(class_9761.java:119) ~[client-intermediary.jar:?]
	at net.minecraft.class_3204.method_60451(class_3204.java:127) ~[client-intermediary.jar:?]
	at net.minecraft.class_3204.redirect$zka000$c2me-fixes-general-threading-issues$replaceIterationForHolderTicking(class_3204.java:1019) ~[client-intermediary.jar:?]
	at net.minecraft.class_3204.method_15892(class_3204.java:127) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_16155(class_3215.java:267) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_12127(class_3215.java:307) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:350) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalStateException: Chunk not there when requested: Unloaded chunk
	at net.minecraft.class_3215.mda667e0$c2me-opts-chunk-access$lambda$c2me$getChunkFutureOffThread$1$3(class_3215.java:4188) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 17 more
[13:29:29] [Server thread/ERROR]: Bumblezone: Failed to teleport entity. Aborting teleportation. Please retry. Entity: class_3222-literal{Amoamogus} Pos: (-570.4787513501669, 102.0, 154.52751450400635) Destination: ResourceKey[minecraft:dimension / the_bumblezone:the_bumblezone]
[13:29:29] [Render thread/INFO]: [System] [CHAT] Failed to teleport entity. Aborting teleportation. Please retry.
```

**Comment by TelepathicGrunt** [comment]
Working for me with Bumblezone alone. Maybe be C2ME issue. 
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/9b2faf94-78bf-43fc-bf51-ab2813f3fb48)

@ishland do you have any idea what might be going on here? I do run a destination check on the off thread so servers don't get stuck waiting for me to find a valid position to teleport players to. Log seems to show c2me angry at the idea
https://github.com/TelepathicGrunt/Bumblezone/blob/dbb4ac62eb255ec3c80245ae017a8da2a6608aa3/common/src/main/java/com/telepathicgrunt/the_bumblezone/utils/ThreadExecutor.java#L153

**Comment by TelepathicGrunt** [comment]
Issue is reproducible only with C2ME on. Definitely seems like something going wrong over there. Not sure what I can do until Ishland can take a look

**Comment by makumaku1974** [comment]
imma try remove C2M

**Comment by TelepathicGrunt** [comment]
Looks like if you turn `generalOptimizations.optimizeAsyncChunkRequest` to false in C2ME's config, teleporting work work again

**Comment by makumaku1974** [comment]
> Looks like if you turn `generalOptimizations.optimizeAsyncChunkRequest` to false in C2ME's config, teleporting work work again

thanks. Is the crash with Bee Sentry fixed? I was using 7.6.2 version of bumblezone testing some other bugs and I thought it would be funny to run into the bee sentry when it's angry... turns out i crashed after. Now im using 7.6.4 bumblezone

**Comment by TelepathicGrunt** [comment]
@makumaku1974 No one reported any crash with the Sentry Watcher. Can you please give me the latest.log file after getting the crash?

**Comment by TelepathicGrunt** [comment]
Yeah I am not crashing with Sentry Watcher 
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/d5aa7da3-1450-445d-acd2-322dd78ccaa1)

Likely you have another mod on that is conflicting. The latest.log file with crash will tell me which mod hopefully

**Comment by makumaku1974** [comment]
> @makumaku1974 No one reported any crash with the Sentry Watcher. Can you please give me the latest.log file after getting the crash?

ill be attempting the crash now.

**Comment by makumaku1974** [comment]
CRASH REPORT:
[Uploading crash-2024-06-23_01.33.43-server.txt…]()

LOG:
[latest.log](https://github.com/user-attachments/files/15937627/latest.log)

**Comment by makumaku1974** [comment]
It does look like Contagion is at fault?

**Comment by TelepathicGrunt** [comment]
@makumaku1974 yep. Contagion is trying to cast my Sentry Watcher as a LivingEntity except it is not a LivingEntity. You’ll have to contact the dev for Contagion and ask them to do an instanceof check before trying to do unsafe casts. They should be making sure the entity is an actual LivingEntity first

**Comment by makumaku1974** [comment]
> @makumaku1974 yep. Contagion is trying to cast my Sentry Watcher as a LivingEntity except it is not a LivingEntity. You’ll have to contact the dev for Contagion and ask them to do an instanceof check before trying to do unsafe casts. They should be making sure the entity is an actual LivingEntity first

I see. This is quite helpful. Thanks

**Comment by makumaku1974** [comment]
> generalOptimizations.optimizeAsyncChunkRequest

There is a problem somehow... It does not show on this config though 
![Screenshot 2024-06-23 031136](https://github.com/TelepathicGrunt/Bumblezone/assets/129804277/1a8c57e5-a892-4ac6-bfc4-d172fb48edf5)

**Comment by TelepathicGrunt** [comment]
The entry to set to false is this one:

![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/14868a4d-db35-4ef2-b3bc-a13fae37eff2)

**Comment by makumaku1974** [comment]
Fully worked im closhing this again.
