### ISSUE TITLE
Crash on Joining world

### ISSUE THREAD

**Issue by Maxi90909** [TelepathicGrunt/Bumblezone#43]
https://pastebin.com/8fUpB1Sc
It won't stop crashing when I try to join

**Comment by TelepathicGrunt** [comment]
I seen this error before and it isn't bumblezone. I believe this is because you are using an outdated version of Optifine (G5). 

Forge did a bugfix for one of its hooks which broke Optifine terrible hacky class replacements. G6 Optifine should stop crashing. On Optifine's download page, click `+ Preview versions` to find the G6 versions. 

let me know if I am right and that fixes the crash. If it doesn't, please post the latest.log file here which can be found in the logs folder above the mods folder

**Comment by Maxi90909** [comment]
It didn't fix It I updated Optifine too G6 and forge to 35.1.37 and it is still crashing

**Comment by Maxi90909** [comment]
[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/5825845/latest.log)
https://pastebin.com/EDCu5u3Z
Here are My logs and the newest crash I had. The crash happened after I joined my minecraft world at this time I had already updated Optifine to G6 and Forge to 35.1.37.

**Comment by TelepathicGrunt** [comment]
The good new is, the previous crash you had was optifine and now that is fixed. The bad new is, the crash you have now is from Survive's compat with Serene Seasons. Try updating both of those mods to latest. If it still crashes, then make an issue report to Survive and show this latest.log file so they can fix their code.

```
Caused by: java.lang.NullPointerException
	at sereneseasons.util.biome.BiomeUtil.getClientBiome(BiomeUtil.java:98) ~[?:1.16.4-4.0.0.86]
	at sereneseasons.util.biome.BiomeUtil.getBiome(BiomeUtil.java:53) ~[?:1.16.4-4.0.0.86]
	at sereneseasons.config.BiomeConfig.usesTropicalSeasons(BiomeConfig.java:65) ~[?:1.16.4-4.0.0.86]
	at com.stereowalker.survive.compat.SereneSeasonsCompat.modifyTemperatureBySeason(SereneSeasonsCompat.java:24) ~[?:1.16.4-3.0.11]
	at com.stereowalker.survive.events.SurviveEvents.updateEnvTemperature(SurviveEvents.java:375) ~[?:1.16.4-3.0.11]
	at net.minecraftforge.eventbus.ASMEventHandler_950_SurviveEvents_updateEnvTemperature_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2550/1630601205.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:320) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
	... 7 more
	```

**Comment by TelepathicGrunt** [comment]
I'll close this report now as it isn't a Bumblezone issue but good luck and I hope the other devs can help you out!

**Comment by Maxi90909** [comment]
I have already posted both issues on both mod Pages but the mods haven’t been updated and I haven’t got a reply yet
